apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: bankdb
  namespace: redis-enterprise2
spec:
  modulesList:
    - name: search
      version: 2.2.6
    - name: timeseries
      version: 1.4.13
  redisEnterpriseCluster:
    name: rec
  shardCount: 2
  shardPlacement: dense
  databasePort: 12869
  databaseSecretName: bankdb-secret
  memorySize: 1GB
